/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './index.html',
    './components/**/*.html',
    './foundations/**/*.html',
    './pages/**/*.html',
    './patterns/**/*.html',
    './templates/**/*.html',
    './navigation/**/*.html',
    './components/**/*.js',
    './styles/**/*.css',
    './src/stories/**/*.js',
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          '50': 'var(--color-primary-50)',
          '100': 'var(--color-primary-100)',
          '200': 'var(--color-primary-200)',
          '300': 'var(--color-primary-300)',
          '400': 'var(--color-primary-400)',
          '500': 'var(--color-primary-500)',
          '600': 'var(--color-primary-600)',
          '700': 'var(--color-primary-700)',
          '800': 'var(--color-primary-800)',
          '900': 'var(--color-primary-900)',
        },
        secondary: {
          '50': 'var(--color-secondary-50)',
          '100': 'var(--color-secondary-100)',
          '200': 'var(--color-secondary-200)',
          '300': 'var(--color-secondary-300)',
          '400': 'var(--color-secondary-400)',
          '500': 'var(--color-secondary-500)',
          '600': 'var(--color-secondary-600)',
          '700': 'var(--color-secondary-700)',
          '800': 'var(--color-secondary-800)',
          '900': 'var(--color-secondary-900)',
        },
        success: {
          '50': 'var(--color-success-50)',
          '100': 'var(--color-success-100)',
          '200': 'var(--color-success-200)',
          '300': 'var(--color-success-300)',
          '400': 'var(--color-success-400)',
          '500': 'var(--color-success-500)',
          '600': 'var(--color-success-600)',
          '700': 'var(--color-success-700)',
          '800': 'var(--color-success-800)',
          '900': 'var(--color-success-900)',
        },
        warning: {
          '50': 'var(--color-warning-50)',
          '100': 'var(--color-warning-100)',
          '200': 'var(--color-warning-200)',
          '300': 'var(--color-warning-300)',
          '400': 'var(--color-warning-400)',
          '500': 'var(--color-warning-500)',
          '600': 'var(--color-warning-600)',
          '700': 'var(--color-warning-700)',
          '800': 'var(--color-warning-800)',
          '900': 'var(--color-warning-900)',
        },
        error: {
          '50': 'var(--color-error-50)',
          '100': 'var(--color-error-100)',
          '200': 'var(--color-error-200)',
          '300': 'var(--color-error-300)',
          '400': 'var(--color-error-400)',
          '500': 'var(--color-error-500)',
          '600': 'var(--color-error-600)',
          '700': 'var(--color-error-700)',
          '800': 'var(--color-error-800)',
          '900': 'var(--color-error-900)',
        },
        info: {
          '50': 'var(--color-info-50)',
          '100': 'var(--color-info-100)',
          '200': 'var(--color-info-200)',
          '300': 'var(--color-info-300)',
          '400': 'var(--color-info-400)',
          '500': 'var(--color-info-500)',
          '600': 'var(--color-info-600)',
          '700': 'var(--color-info-700)',
          '800': 'var(--color-info-800)',
          '900': 'var(--color-info-900)',
        },
        gray: {
          '50': 'var(--color-gray-50)',
          '100': 'var(--color-gray-100)',
          '200': 'var(--color-gray-200)',
          '300': 'var(--color-gray-300)',
          '400': 'var(--color-gray-400)',
          '500': 'var(--color-gray-500)',
          '600': 'var(--color-gray-600)',
          '700': 'var(--color-gray-700)',
          '800': 'var(--color-gray-800)',
          '900': 'var(--color-gray-900)',
        },
        blue: {
          '50': 'var(--color-blue-b50)',
          '75': 'var(--color-blue-b75)',
          '100': 'var(--color-blue-b100)',
          '200': 'var(--color-blue-b200)',
          '300': 'var(--color-blue-b300)',
          '400': 'var(--color-blue-b400)',
          '500': 'var(--color-blue-b500)',
        },
        orange: {
          '50': 'var(--color-orange-o50)',
          '75': 'var(--color-orange-o75)',
          '100': 'var(--color-orange-o100)',
          '200': 'var(--color-orange-o200)',
          '300': 'var(--color-orange-o300)',
          '400': 'var(--color-orange-o400)',
          '500': 'var(--color-orange-o500)',
        },
        red: {
          '50': 'var(--color-red-r50)',
          '75': 'var(--color-red-r75)',
          '100': 'var(--color-red-r100)',
          '200': 'var(--color-red-r200)',
          '300': 'var(--color-red-r300)',
          '400': 'var(--color-red-r400)',
          '500': 'var(--color-red-r500)',
        },
        green: {
          '50': 'var(--color-green-g50)',
          '75': 'var(--color-green-g75)',
          '100': 'var(--color-green-g100)',
          '200': 'var(--color-green-g200)',
          '300': 'var(--color-green-g300)',
          '400': 'var(--color-green-g400)',
          '500': 'var(--color-green-g500)',
        },
        purple: {
          '50': 'var(--color-purple-p50)',
          '75': 'var(--color-purple-p75)',
          '100': 'var(--color-purple-p100)',
          '200': 'var(--color-purple-p200)',
          '300': 'var(--color-purple-p300)',
          '400': 'var(--color-purple-p400)',
          '500': 'var(--color-purple-p500)',
        },
        neutral: {
          '0': 'var(--color-neutral-n0)',
          '10': 'var(--color-neutral-n10)',
          '20': 'var(--color-neutral-n20)',
          '30': 'var(--color-neutral-n30)',
          '40': 'var(--color-neutral-n40)',
          '50': 'var(--color-neutral-n50)',
          '60': 'var(--color-neutral-n60)',
          '70': 'var(--color-neutral-n70)',
          '80': 'var(--color-neutral-n80)',
          '90': 'var(--color-neutral-n90)',
          '100': 'var(--color-neutral-n100)',
          '200': 'var(--color-neutral-n200)',
          '300': 'var(--color-neutral-n300)',
          '400': 'var(--color-neutral-n400)',
          '500': 'var(--color-neutral-n500)',
          '600': 'var(--color-neutral-n600)',
          '700': 'var(--color-neutral-n700)',
          '800': 'var(--color-neutral-n800)',
          '900': 'var(--color-neutral-n900)',
        },
        background: 'var(--color-background)',
        surface: 'var(--color-surface)',
        border: {
          DEFAULT: 'var(--color-border)',
          light: 'var(--color-border-light)',
          brand: 'var(--color-border-brand)',
        },
        text: {
          primary: 'var(--color-text-primary)',
          secondary: 'var(--color-text-secondary)',
          tertiary: 'var(--color-text-tertiary)',
          disabled: 'var(--color-text-disabled)',
          inverse: 'var(--color-text-inverse)',
          brand: 'var(--color-text-brand)',
          code: 'var(--color-text-code)',
        },
        sidebar: {
          DEFAULT: 'var(--sidebar-bg)',
          header: 'var(--sidebar-header-bg)',
          border: 'var(--sidebar-border)',
          logo: 'var(--sidebar-logo-color)',
          version: 'var(--sidebar-version-color)',
          section: 'var(--sidebar-section-title)',
          link: 'var(--sidebar-link-color)',
          'link-hover': 'var(--sidebar-link-hover-color)',
          'link-active': 'var(--sidebar-link-active-color)',
          'link-active-border': 'var(--sidebar-link-active-border)',
          search: 'var(--sidebar-search-bg)',
          footer: 'var(--sidebar-footer-bg)',
        },
        topbar: {
          DEFAULT: 'var(--topbar-bg)',
          border: 'var(--topbar-border)',
        },
      },
      fontFamily: {
        primary: ['var(--font-primary)'],
        sans: ['var(--font-primary)'],
      },
      fontSize: {
        'xs': 'var(--font-size-xs)',
        'sm': 'var(--font-size-sm)',
        'base': 'var(--font-size-base)',
        'lg': 'var(--font-size-lg)',
        'xl': 'var(--font-size-xl)',
        '2xl': 'var(--font-size-2xl)',
        '3xl': 'var(--font-size-3xl)',
        '4xl': 'var(--font-size-4xl)',
        '5xl': 'var(--font-size-5xl)',
        'caption': 'var(--text-caption-regular-size)',
        'overline': 'var(--text-overline-medium-size)',
        'body-sm': 'var(--text-body-small-regular-size)',
        'body-md': 'var(--text-body-medium-regular-size)',
        'body-lg': 'var(--text-body-large-regular-size)',
        'title': 'var(--text-title-medium-size)',
      },
      fontWeight: {
        'light': 'var(--font-weight-light)',
        'normal': 'var(--font-weight-normal)',
        'medium': 'var(--font-weight-medium)',
        'semibold': 'var(--font-weight-semibold)',
        'bold': 'var(--font-weight-bold)',
      },
      lineHeight: {
        'tight': 'var(--line-height-tight)',
        'snug': 'var(--line-height-snug)',
        'normal': 'var(--line-height-normal)',
        'relaxed': 'var(--line-height-relaxed)',
        'loose': 'var(--line-height-loose)',
        'body-sm': 'var(--text-body-small-regular-lh)',
        'caption': 'var(--text-caption-regular-lh)',
        'overline': 'var(--text-overline-medium-lh)',
      },
      letterSpacing: {
        'tight': 'var(--letter-spacing-tight)',
        'normal': 'var(--letter-spacing-normal)',
        'wide': 'var(--letter-spacing-wide)',
        'wider': 'var(--letter-spacing-wider)',
        'overline': 'var(--text-overline-medium-ls)',
      },
      spacing: {
        '0': 'var(--space-0)',
        '025': 'var(--space-025)',
        '050': 'var(--space-050)',
        '075': 'var(--space-075)',
        '100': 'var(--space-100)',
        '150': 'var(--space-150)',
        '200': 'var(--space-200)',
        '250': 'var(--space-250)',
        '300': 'var(--space-300)',
        '400': 'var(--space-400)',
        '500': 'var(--space-500)',
        '600': 'var(--space-600)',
        '800': 'var(--space-800)',
        '1000': 'var(--space-1000)',
        '1': 'var(--spacing-1)',
        '2': 'var(--spacing-2)',
        '3': 'var(--spacing-3)',
        '4': 'var(--spacing-4)',
        '5': 'var(--spacing-5)',
        '6': 'var(--spacing-6)',
        '8': 'var(--spacing-8)',
        '10': 'var(--spacing-10)',
        '12': 'var(--spacing-12)',
        '16': 'var(--spacing-16)',
        '20': 'var(--spacing-20)',
        '24': 'var(--spacing-24)',
      },
      borderRadius: {
        'none': 'var(--border-radius-none)',
        'sm': 'var(--border-radius-sm)',
        'md': 'var(--border-radius-md)',
        'lg': 'var(--border-radius-lg)',
        'xl': 'var(--border-radius-xl)',
        '2xl': 'var(--border-radius-2xl)',
        '3xl': 'var(--border-radius-3xl)',
        'full': 'var(--border-radius-full)',
      },
      borderWidth: {
        '0': 'var(--border-width-0)',
        '1': 'var(--border-width-1)',
        '2': 'var(--border-width-2)',
        '4': 'var(--border-width-4)',
      },
      boxShadow: {
        '1': 'var(--shadow-1)',
        'xs': 'var(--shadow-xs)',
        'sm': 'var(--shadow-sm)',
        'md': 'var(--shadow-md)',
        'lg': 'var(--shadow-lg)',
        'xl': 'var(--shadow-xl)',
        '2xl': 'var(--shadow-2xl)',
        'brand': 'var(--shadow-brand)',
        'inner': 'var(--shadow-inner)',
        'none': 'var(--shadow-none)',
      },
      zIndex: {
        'hide': 'var(--z-hide)',
        'base': 'var(--z-base)',
        'dropdown': 'var(--z-dropdown)',
        'sticky': 'var(--z-sticky)',
        'fixed': 'var(--z-fixed)',
        'modal-backdrop': 'var(--z-modal-backdrop)',
        'modal': 'var(--z-modal)',
        'popover': 'var(--z-popover)',
        'tooltip': 'var(--z-tooltip)',
      },
      transitionDuration: {
        fast: '150ms',
        base: '200ms',
        slow: '300ms',
        spring: '400ms',
      },
      transitionTimingFunction: {
        'ease-in-out': 'ease-in-out',
        spring: 'cubic-bezier(0.175,0.885,0.32,1.275)',
      },
      screens: {
        xs: '0px',
        sm: '640px',
        md: '768px',
        lg: '1024px',
        xl: '1280px',
        '2xl': '1536px',
      },
    },
  },
  plugins: [],
};
