export const GENERAL = [
  { file: 'icon-adjustments-horizontal.svg',        name: 'AdjustmentsHorizontal'      },
  { file: 'icon-archive-box.svg',                   name: 'ArchiveBox'                  },
  { file: 'icon-arrow-down-on-square.svg',          name: 'ArrowDownOnSquare'           },
  { file: 'icon-arrow-down-tray.svg',               name: 'ArrowDownTray'               },
  { file: 'icon-arrow-left.svg',                    name: 'ArrowLeft'                   },
  { file: 'icon-arrow-left-on-rectangle.svg',       name: 'ArrowLeftOnRectangle'        },
  { file: 'icon-arrow-path.svg',                    name: 'ArrowPath'                   },
  { file: 'icon-arrow-right-on-rectangle.svg',      name: 'ArrowRightOnRectangle'       },
  { file: 'icon-arrow-up-tray.svg',                 name: 'ArrowUpTray'                 },
  { file: 'icon-arrows-right-left.svg',             name: 'ArrowsRightLeft'             },
  { file: 'icon-arrows-up-down.svg',                name: 'ArrowsUpDown'                },
  { file: 'icon-at-symbol.svg',                     name: 'AtSymbol'                    },
  { file: 'icon-banknotes.svg',                     name: 'Banknotes'                   },
  { file: 'icon-bars3-bottom-left.svg',             name: 'Bars3BottomLeft'             },
  { file: 'icon-beaker.svg',                        name: 'Beaker'                      },
  { file: 'icon-bell.svg',                          name: 'Bell'                        },
  { file: 'icon-bell-alert.svg',                    name: 'BellAlert'                   },
  { file: 'icon-bolt.svg',                          name: 'Bolt'                        },
  { file: 'icon-book-open.svg',                     name: 'BookOpen'                    },
  { file: 'icon-calculator.svg',                    name: 'Calculator'                  },
  { file: 'icon-calendar-days.svg',                 name: 'CalendarDays'                },
  { file: 'icon-camera.svg',                        name: 'Camera'                      },
  { file: 'icon-chart-pie.svg',                     name: 'ChartPie'                    },
  { file: 'icon-chat-bubble-left.svg',              name: 'ChatBubbleLeft'              },
  { file: 'icon-chat-bubble-left-right.svg',        name: 'ChatBubbleLeftRight'         },
  { file: 'icon-check.svg',                         name: 'Check'                       },
  { file: 'icon-clipboard.svg',                     name: 'Clipboard'                   },
  { file: 'icon-clipboard-document-list.svg',       name: 'ClipboardDocumentList'       },
  { file: 'icon-clock.svg',                         name: 'Clock'                       },
  { file: 'icon-cog6-tooth.svg',                    name: 'Cog6Tooth'                   },
  { file: 'icon-credit-card.svg',                   name: 'CreditCard'                  },
  { file: 'icon-document.svg',                      name: 'Document'                    },
  { file: 'icon-document-check.svg',                name: 'DocumentCheck'               },
  { file: 'icon-document-text.svg',                 name: 'DocumentText'                },
  { file: 'icon-ellipsis-vertical.svg',             name: 'EllipsisVertical'            },
  { file: 'icon-envelope.svg',                      name: 'Envelope'                    },
  { file: 'icon-eye.svg',                           name: 'Eye'                         },
  { file: 'icon-eye-slash.svg',                     name: 'EyeSlash'                    },
  { file: 'icon-menu.svg',                          name: 'Menu'                        },
  { file: 'icon-pdf.svg',                           name: 'PDF'                         },
  { file: 'icon-solid-check-badge.svg',             name: 'SolidCheckBadge'             },
  { file: 'icon-solid-check-circle.svg',            name: 'SolidCheckCircle'            },
  { file: 'icon-arrow-down-on-square-stack.svg',    name: 'ArrowDownOnSquareStack'      },
  { file: 'icon-arrow-right.svg',                   name: 'ArrowRight'                  },
  { file: 'icon-arrow-trending-down.svg',           name: 'ArrowTrendingDown'           },
  { file: 'icon-arrow-trending-up.svg',             name: 'ArrowTrendingUp'             },
  { file: 'icon-arrow-up-on-square-stack.svg',      name: 'ArrowUpOnSquareStack'        },
  { file: 'icon-arrow-up-on-square.svg',            name: 'ArrowUpOnSquare'             },
  { file: 'icon-arrow-uturn-left.svg',              name: 'ArrowUturnLeft'              },
  { file: 'icon-arrow-top-tight-on-square.svg',     name: 'ArrowTopTightOnSquare'       },
  { file: 'icon-chevron-down.svg',                  name: 'ChevronDown'                 },
  { file: 'icon-chevron-left.svg',                  name: 'ChevronLeft'                 },
  { file: 'icon-chevron-mini-down.svg',             name: 'ChevronMiniDown'             },
  { file: 'icon-chevron-mini-left.svg',             name: 'ChevronMiniLeft'             },
  { file: 'icon-chevron-mini-right.svg',            name: 'ChevronMiniRight'            },
  { file: 'icon-chevron-mini-up.svg',               name: 'ChevronMiniUp'               },
  { file: 'icon-chevron-right.svg',                 name: 'ChevronRight'                },
  { file: 'icon-chevron-up.svg',                    name: 'ChevronUp'                   },
  { file: 'icon-folder-open.svg',                   name: 'FolderOpen'                  },
  { file: 'icon-folder.svg',                        name: 'Folder'                      },
  { file: 'icon-funnel.svg',                        name: 'Funnel'                      },
  { file: 'icon-home.svg',                          name: 'Home'                        },
  { file: 'icon-identification.svg',                name: 'Identification'              },
  { file: 'icon-key.svg',                           name: 'Key'                         },
  { file: 'icon-lifebuoy.svg',                      name: 'Lifebuoy'                    },
  { file: 'icon-light-bulb.svg',                    name: 'LightBulb'                   },
  { file: 'icon-link.svg',                          name: 'Link'                        },
  { file: 'icon-lock-closed.svg',                   name: 'LockClosed'                  },
  { file: 'icon-magnifying-glass.svg',              name: 'MagnifyingGlass'             },
  { file: 'icon-map-pin.svg',                       name: 'MapPin'                      },
  { file: 'icon-mini-arrow-top-right-on-square.svg', name: 'MiniArrowTopRightOnSquare' },
  { file: 'icon-minus-circle-outline.svg',          name: 'MinusCircleOutline'          },
  { file: 'icon-minus.svg',                         name: 'Minus'                       },
  { file: 'icon-money.svg',                         name: 'Money'                       },
  { file: 'icon-newspaper.svg',                     name: 'Newspaper'                   },
  { file: 'icon-no-symbol.svg',                     name: 'NoSymbol'                    },
  { file: 'icon-paper-airplane.svg',                name: 'PaperAirplane'               },
  { file: 'icon-paper-clip.svg',                    name: 'PaperClip'                   },
  { file: 'icon-pencil-square.svg',                 name: 'PencilSquare'                },
  { file: 'icon-pencil.svg',                        name: 'Pencil'                      },
  { file: 'icon-percent.svg',                       name: 'Percent'                     },
  { file: 'icon-phone.svg',                         name: 'Phone'                       },
  { file: 'icon-photo.svg',                         name: 'Photo'                       },
  { file: 'icon-plus-circle-filled.svg',            name: 'PlusCircleFilled'            },
  { file: 'icon-plus-circle-outline.svg',           name: 'PlusCircleOutline'           },
  { file: 'icon-plus.svg',                          name: 'Plus'                        },
  { file: 'icon-point.svg',                         name: 'Point'                       },
  { file: 'icon-printer.svg',                       name: 'Printer'                     },
  { file: 'icon-receipt-percent.svg',               name: 'ReceiptPercent'              },
  { file: 'icon-receipt-refund.svg',                name: 'ReceiptRefund'               },
  { file: 'icon-rupiah.svg',                        name: 'Rupiah'                      },
  { file: 'icon-share.svg',                         name: 'Share'                       },
  { file: 'icon-shopping-bag.svg',                  name: 'ShoppingBag'                 },
  { file: 'icon-shopping-cart.svg',                 name: 'ShoppingCart'                },
  { file: 'icon-solid-adjustments-horizontal.svg',  name: 'SolidAdjustmentsHorizontal'  },
  { file: 'icon-solid-exclamation-triangle.svg',    name: 'SolidExclamationTriangle'    },
  { file: 'icon-solid-information-circle.svg',      name: 'SolidInformationCircle'      },
  { file: 'icon-solid-question-mark-circle.svg',    name: 'SolidQuestionMarkCircle'     },
  { file: 'icon-solid-shield-check.svg',            name: 'SolidShieldCheck'            },
  { file: 'icon-solid-sparkles.svg',                name: 'SolidSparkles'               },
  { file: 'icon-square-2-stack.svg',                name: 'Square2Stack'                },
  { file: 'icon-squares-plus.svg',                  name: 'SquaresPlus'                 },
  { file: 'icon-table-cells.svg',                   name: 'TableCells'                  },
  { file: 'icon-tag.svg',                           name: 'Tag'                         },
  { file: 'icon-trash.svg',                         name: 'Trash'                       },
  { file: 'icon-user-group.svg',                    name: 'UserGroup'                   },
  { file: 'icon-user.svg',                          name: 'User'                        },
  { file: 'icon-wallet.svg',                        name: 'Wallet'                      },
  { file: 'icon-x-circle-outline.svg',              name: 'XCircleOutline'              },
  { file: 'icon-x-mark.svg',                        name: 'XMark'                       },
];

export const OFFLINE = [
  { name: 'App',               off: 'icon-sidebar-offline-app-off.svg',                 on: 'icon-sidebar-offline-app-on.svg'                },
  { name: 'Belanja',           off: 'icon-sidebar-offline-belanja-off.svg',             on: 'icon-sidebar-offline-belanja-on.svg'            },
  { name: 'Customer',          off: 'icon-sidebar-offline-customer-off.svg',            on: 'icon-sidebar-offline-customer-on.svg'           },
  { name: 'Guide',             off: 'icon-sidebar-offline-guide-off.svg',               on: 'icon-sidebar-offline-guide-on.svg'              },
  { name: 'Inventory',         off: 'icon-sidebar-offline-inventory-off.svg',           on: 'icon-sidebar-offline-inventory-on.svg'          },
  { name: 'Invoice',           off: 'icon-sidebar-offline-invoice-off.svg',             on: 'icon-sidebar-offline-invoice-on.svg'            },
  { name: 'Kas & Bank',        off: 'icon-sidebar-offline-kas-bank-off.svg',            on: 'icon-sidebar-offline-kas-bank-on.svg'           },
  { name: 'News',              off: 'icon-sidebar-offline-news-off.svg',                on: 'icon-sidebar-offline-news-on.svg'               },
  { name: 'Online',            off: 'icon-sidebar-offline-online-off.svg',              on: 'icon-sidebar-offline-online-on.svg'             },
  { name: 'POS',               off: 'icon-sidebar-offline-pos-off.svg',                 on: 'icon-sidebar-offline-pos-on.svg'                },
  { name: 'Product',           off: 'icon-sidebar-offline-product-off.svg',             on: 'icon-sidebar-offline-product-on.svg'            },
  { name: 'Report',            off: 'icon-sidebar-offline-report-off.svg',              on: 'icon-sidebar-offline-report-on.svg'             },
  { name: 'Setting',           off: 'icon-sidebar-offline-setting-off.svg',             on: 'icon-sidebar-offline-setting-on.svg'            },
  { name: 'Tebus Murah',       off: 'icon-sidebar-offline-tebus-murah-off.svg',         on: 'icon-sidebar-offline-tebus-murah-on.svg'        },
  { name: 'Company',           off: 'icon-sidebar-offline-company-off.svg',             on: 'icon-sidebar-offline-company-on.svg'            },
  { name: 'Dashboard',         off: 'icon-sidebar-offline-dashboard-off.svg',           on: 'icon-sidebar-offline-dashboard-on.svg'          },
  { name: 'Finance',           off: 'icon-sidebar-offline-finance-off.svg',             on: 'icon-sidebar-offline-finance-on.svg'            },
  { name: 'Jejaring Pesan',    off: 'icon-sidebar-offline-jejaring-pesan-off.svg',      on: 'icon-sidebar-offline-jejaring-pesan-on.svg'     },
  { name: 'Ledger',            off: 'icon-sidebar-offline-ledger-off.svg',              on: 'icon-sidebar-offline-ledger-on.svg'             },
  { name: 'Master',            off: 'icon-sidebar-offline-master-off.svg',              on: 'icon-sidebar-offline-master-on.svg'             },
  { name: 'Medikal',           off: 'icon-sidebar-offline-medikal-off.svg',             on: 'icon-sidebar-offline-medikal-on.svg'            },
  { name: 'Megaphone',         off: 'icon-sidebar-offline-megaphone-off.svg',           on: 'icon-sidebar-offline-megaphone-on.svg'          },
  { name: 'Payable',           off: 'icon-sidebar-offline-payable-off.svg',             on: 'icon-sidebar-offline-payable-on.svg'            },
  { name: 'Principal',         off: 'icon-sidebar-offline-principal-off.svg',           on: 'icon-sidebar-offline-principal-on.svg'          },
  { name: 'Smart Forecasting', off: 'icon-sidebar-offline-smart-forecasrting-off.svg',  on: 'icon-sidebar-offline-smart-forecasrting-on.svg' },
];

export const ONLINE = [
  { name: 'Chat',         off: 'icon-sidebar-online-chat-off.svg',         on: 'icon-sidebar-online-chat-on.svg'         },
  { name: 'Dashboard',    off: 'icon-sidebar-online-dashboard-off.svg',    on: 'icon-sidebar-online-dashboard-on.svg'    },
  { name: 'Dekorasi',     off: 'icon-sidebar-online-dekorasi-off.svg',     on: 'icon-sidebar-online-dekorasi-on.svg'     },
  { name: 'Help',         off: 'icon-sidebar-online-help-off.svg',         on: 'icon-sidebar-online-help-on.svg'         },
  { name: 'Laporan',      off: 'icon-sidebar-online-laporan-off.svg',      on: 'icon-sidebar-online-laporan-on.svg'      },
  { name: 'Notification', off: 'icon-sidebar-online-notification-off.svg', on: 'icon-sidebar-online-notification-on.svg' },
  { name: 'Pesanan',      off: 'icon-sidebar-online-pesanan-off.svg',      on: 'icon-sidebar-online-pesanan-on.svg'      },
  { name: 'Produk',       off: 'icon-sidebar-online-produk-off.svg',       on: 'icon-sidebar-online-produk-on.svg'       },
  { name: 'Promo',        off: 'icon-sidebar-online-promo-off.svg',        on: 'icon-sidebar-online-promo-on.svg'        },
  { name: 'Resep',        off: 'icon-sidebar-online-resep-off.svg',        on: 'icon-sidebar-online-resep-on.svg'        },
  { name: 'User',         off: 'icon-sidebar-online-user-off.svg',         on: 'icon-sidebar-online-user-on.svg'         },
];

export const sizes = [
  { token: 'small',  px: '16px', tw: 'w-4 h-4',   cssVar: '--icon-size-small',  ctx: 'Badge, chip, inline icon'     },
  { token: 'medium', px: '24px', tw: 'w-6 h-6',   cssVar: '--icon-size-medium', ctx: 'Button, input, nav item'      },
  { token: 'large',  px: '32px', tw: 'w-8 h-8',   cssVar: '--icon-size-large',  ctx: 'Card header, empty state'     },
  { token: 'xlarge', px: '48px', tw: 'w-12 h-12', cssVar: '--icon-size-xlarge', ctx: 'Hero, error page, onboarding' },
];
