export const GENERAL = [
  { file: 'Icon:AdjustmentsHorizontal.svg',        name: 'AdjustmentsHorizontal'      },
  { file: 'Icon:ArchiveBox.svg',                   name: 'ArchiveBox'                  },
  { file: 'Icon:ArrowDownOnSquare.svg',            name: 'ArrowDownOnSquare'           },
  { file: 'Icon:ArrowDownTray.svg',                name: 'ArrowDownTray'               },
  { file: 'Icon:ArrowLeft.svg',                    name: 'ArrowLeft'                   },
  { file: 'Icon:ArrowLeftOnRectangle.svg',         name: 'ArrowLeftOnRectangle'        },
  { file: 'Icon:ArrowPath.svg',                    name: 'ArrowPath'                   },
  { file: 'Icon:ArrowRightOnRectangle.svg',        name: 'ArrowRightOnRectangle'       },
  { file: 'Icon:ArrowUpTray.svg',                  name: 'ArrowUpTray'                 },
  { file: 'Icon:ArrowsRightLeft.svg',              name: 'ArrowsRightLeft'             },
  { file: 'Icon:ArrowsUpDown.svg',                 name: 'ArrowsUpDown'                },
  { file: 'Icon:AtSymbol.svg',                     name: 'AtSymbol'                    },
  { file: 'Icon:Banknotes.svg',                    name: 'Banknotes'                   },
  { file: 'Icon:Bars3BottomLeft.svg',              name: 'Bars3BottomLeft'             },
  { file: 'Icon:Beaker.svg',                       name: 'Beaker'                      },
  { file: 'Icon:Bell.svg',                         name: 'Bell'                        },
  { file: 'Icon:BellAlert.svg',                    name: 'BellAlert'                   },
  { file: 'Icon:Bolt.svg',                         name: 'Bolt'                        },
  { file: 'Icon:BookOpen.svg',                     name: 'BookOpen'                    },
  { file: 'Icon:Calculator.svg',                   name: 'Calculator'                  },
  { file: 'Icon:CalendarDays.svg',                 name: 'CalendarDays'                },
  { file: 'Icon:Camera.svg',                       name: 'Camera'                      },
  { file: 'Icon:ChartPie.svg',                     name: 'ChartPie'                    },
  { file: 'Icon:ChatBubbleLeft.svg',               name: 'ChatBubbleLeft'              },
  { file: 'Icon:ChatBubbleLeftRight.svg',          name: 'ChatBubbleLeftRight'         },
  { file: 'Icon:Check.svg',                        name: 'Check'                       },
  { file: 'Icon:Clipboard.svg',                    name: 'Clipboard'                   },
  { file: 'Icon:ClipboardDocumentList.svg',        name: 'ClipboardDocumentList'       },
  { file: 'Icon:Clock.svg',                        name: 'Clock'                       },
  { file: 'Icon:Cog6Tooth.svg',                    name: 'Cog6Tooth'                   },
  { file: 'Icon:CreditCard.svg',                   name: 'CreditCard'                  },
  { file: 'Icon:Document.svg',                     name: 'Document'                    },
  { file: 'Icon:DocumentCheck.svg',                name: 'DocumentCheck'               },
  { file: 'Icon:DocumentText.svg',                 name: 'DocumentText'                },
  { file: 'Icon:EllipsisVertical.svg',             name: 'EllipsisVertical'            },
  { file: 'Icon:Envelope.svg',                     name: 'Envelope'                    },
  { file: 'Icon:Eye.svg',                          name: 'Eye'                         },
  { file: 'Icon:EyeSlash.svg',                     name: 'EyeSlash'                    },
  { file: 'Icon:Menu.svg',                         name: 'Menu'                        },
  { file: 'Icon:PDF.svg',                          name: 'PDF'                         },
  { file: 'Icon:SolidCheckBadge.svg',              name: 'SolidCheckBadge'             },
  { file: 'Icon:SolidCheckCircle.svg',             name: 'SolidCheckCircle'            },
  { file: 'Icon:arrow-down-on-square-stack.svg',   name: 'ArrowDownOnSquareStack'      },
  { file: 'Icon:arrow-right.svg',                  name: 'ArrowRight'                  },
  { file: 'Icon:arrow-trending-down.svg',          name: 'ArrowTrendingDown'           },
  { file: 'Icon:arrow-trending-up.svg',            name: 'ArrowTrendingUp'             },
  { file: 'Icon:arrow-up-on-square-stack.svg',     name: 'ArrowUpOnSquareStack'        },
  { file: 'Icon:arrow-up-on-square.svg',           name: 'ArrowUpOnSquare'             },
  { file: 'Icon:arrow-uturn-left.svg',             name: 'ArrowUturnLeft'              },
  { file: 'Icon:arrowTopTightOnSquare.svg',        name: 'ArrowTopTightOnSquare'       },
  { file: 'Icon:chevron-down.svg',                 name: 'ChevronDown'                 },
  { file: 'Icon:chevron-left.svg',                 name: 'ChevronLeft'                 },
  { file: 'Icon:chevron-mini-down.svg',            name: 'ChevronMiniDown'             },
  { file: 'Icon:chevron-mini-left.svg',            name: 'ChevronMiniLeft'             },
  { file: 'Icon:chevron-mini-right.svg',           name: 'ChevronMiniRight'            },
  { file: 'Icon:chevron-mini-up.svg',              name: 'ChevronMiniUp'               },
  { file: 'Icon:chevron-right.svg',                name: 'ChevronRight'                },
  { file: 'Icon:chevron-up.svg',                   name: 'ChevronUp'                   },
  { file: 'Icon:folder-open.svg',                  name: 'FolderOpen'                  },
  { file: 'Icon:folder.svg',                       name: 'Folder'                      },
  { file: 'Icon:funnel.svg',                       name: 'Funnel'                      },
  { file: 'Icon:home.svg',                         name: 'Home'                        },
  { file: 'Icon:identification.svg',               name: 'Identification'              },
  { file: 'Icon:key.svg',                          name: 'Key'                         },
  { file: 'Icon:lifebuoy.svg',                     name: 'Lifebuoy'                    },
  { file: 'Icon:light-bulb.svg',                   name: 'LightBulb'                   },
  { file: 'Icon:link.svg',                         name: 'Link'                        },
  { file: 'Icon:lock-closed.svg',                  name: 'LockClosed'                  },
  { file: 'Icon:magnifying-glass.svg',             name: 'MagnifyingGlass'             },
  { file: 'Icon:map-pin.svg',                      name: 'MapPin'                      },
  { file: 'Icon:miniArrowTopRightOnSquare.svg',    name: 'MiniArrowTopRightOnSquare'   },
  { file: 'Icon:minus-circle-outline.svg',         name: 'MinusCircleOutline'          },
  { file: 'Icon:minus.svg',                        name: 'Minus'                       },
  { file: 'Icon:money.svg',                        name: 'Money'                       },
  { file: 'Icon:newspaper.svg',                    name: 'Newspaper'                   },
  { file: 'Icon:no-symbol.svg',                    name: 'NoSymbol'                    },
  { file: 'Icon:paper-airplane.svg',               name: 'PaperAirplane'               },
  { file: 'Icon:paper-clip.svg',                   name: 'PaperClip'                   },
  { file: 'Icon:pencil-square.svg',                name: 'PencilSquare'                },
  { file: 'Icon:pencil.svg',                       name: 'Pencil'                      },
  { file: 'Icon:percent.svg',                      name: 'Percent'                     },
  { file: 'Icon:phone.svg',                        name: 'Phone'                       },
  { file: 'Icon:photo.svg',                        name: 'Photo'                       },
  { file: 'Icon:plus-circle-filled.svg',           name: 'PlusCircleFilled'            },
  { file: 'Icon:plus-circle-outline.svg',          name: 'PlusCircleOutline'           },
  { file: 'Icon:plus.svg',                         name: 'Plus'                        },
  { file: 'Icon:point.svg',                        name: 'Point'                       },
  { file: 'Icon:printer.svg',                      name: 'Printer'                     },
  { file: 'Icon:receipt-percent.svg',              name: 'ReceiptPercent'              },
  { file: 'Icon:receipt-refund.svg',               name: 'ReceiptRefund'               },
  { file: 'Icon:rupiah.svg',                       name: 'Rupiah'                      },
  { file: 'Icon:share.svg',                        name: 'Share'                       },
  { file: 'Icon:shopping-bag.svg',                 name: 'ShoppingBag'                 },
  { file: 'Icon:shopping-cart.svg',                name: 'ShoppingCart'                },
  { file: 'Icon:solid-adjustments-horizontal.svg', name: 'SolidAdjustmentsHorizontal'  },
  { file: 'Icon:solid-exclamation-triangle.svg',   name: 'SolidExclamationTriangle'    },
  { file: 'Icon:solid-information-circle.svg',     name: 'SolidInformationCircle'      },
  { file: 'Icon:solid-question-mark-circle.svg',   name: 'SolidQuestionMarkCircle'     },
  { file: 'Icon:solid-shield-check.svg',           name: 'SolidShieldCheck'            },
  { file: 'Icon:solid-sparkles.svg',               name: 'SolidSparkles'               },
  { file: 'Icon:square-2-stack.svg',               name: 'Square2Stack'                },
  { file: 'Icon:squares-plus.svg',                 name: 'SquaresPlus'                 },
  { file: 'Icon:table-cells.svg',                  name: 'TableCells'                  },
  { file: 'Icon:tag.svg',                          name: 'Tag'                         },
  { file: 'Icon:trash.svg',                        name: 'Trash'                       },
  { file: 'Icon:user-group.svg',                   name: 'UserGroup'                   },
  { file: 'Icon:user.svg',                         name: 'User'                        },
  { file: 'Icon:wallet.svg',                       name: 'Wallet'                      },
  { file: 'Icon:x-circle-outline.svg',             name: 'XCircleOutline'              },
  { file: 'Icon:x-mark.svg',                       name: 'XMark'                       },
];

export const OFFLINE = [
  { name: 'App',               off: 'icon:sidebar offline:App:Off.svg',                on: 'icon:sidebar offline:App:On.svg'                },
  { name: 'Belanja',           off: 'icon:sidebar offline:Belanja:Off.svg',            on: 'icon:sidebar offline:Belanja:On.svg'            },
  { name: 'Customer',          off: 'icon:sidebar offline:Customer:Off.svg',           on: 'icon:sidebar offline:Customer:On.svg'           },
  { name: 'Guide',             off: 'icon:sidebar offline:Guide:Off.svg',              on: 'icon:sidebar offline:Guide:On.svg'              },
  { name: 'Inventory',         off: 'icon:sidebar offline:Inventory:Off.svg',          on: 'icon:sidebar offline:Inventory:On.svg'          },
  { name: 'Invoice',           off: 'icon:sidebar offline:Invoice:Off.svg',            on: 'icon:sidebar offline:Invoice:On.svg'            },
  { name: 'Kas & Bank',        off: 'icon:sidebar offline:Kas & bank:Off.svg',         on: 'icon:sidebar offline:Kas & bank:On.svg'         },
  { name: 'News',              off: 'icon:sidebar offline:News:Off.svg',               on: 'icon:sidebar offline:News:On.svg'               },
  { name: 'Online',            off: 'icon:sidebar offline:Online:Off.svg',             on: 'icon:sidebar offline:Online:On.svg'             },
  { name: 'POS',               off: 'icon:sidebar offline:POS:Off.svg',                on: 'icon:sidebar offline:POS:On.svg'                },
  { name: 'Product',           off: 'icon:sidebar offline:Product:Off.svg',            on: 'icon:sidebar offline:Product:On.svg'            },
  { name: 'Report',            off: 'icon:sidebar offline:Report:Off.svg',             on: 'icon:sidebar offline:Report:On.svg'             },
  { name: 'Setting',           off: 'icon:sidebar offline:Setting:Off.svg',            on: 'icon:sidebar offline:Setting:On.svg'            },
  { name: 'Tebus Murah',       off: 'icon:sidebar offline:Tebus Murah:Off.svg',        on: 'icon:sidebar offline:Tebus Murah:On.svg'        },
  { name: 'Company',           off: 'icon:sidebar offline:company:Off.svg',            on: 'icon:sidebar offline:company:On.svg'            },
  { name: 'Dashboard',         off: 'icon:sidebar offline:dashboard:Off.svg',          on: 'icon:sidebar offline:dashboard:On.svg'          },
  { name: 'Finance',           off: 'icon:sidebar offline:finance:Off.svg',            on: 'icon:sidebar offline:finance:On.svg'            },
  { name: 'Jejaring Pesan',    off: 'icon:sidebar offline:jejaring pesan:Off.svg',     on: 'icon:sidebar offline:jejaring pesan:On.svg'     },
  { name: 'Ledger',            off: 'icon:sidebar offline:ledger:Off.svg',             on: 'icon:sidebar offline:ledger:On.svg'             },
  { name: 'Master',            off: 'icon:sidebar offline:master:Off.svg',             on: 'icon:sidebar offline:master:On.svg'             },
  { name: 'Medikal',           off: 'icon:sidebar offline:medikal:Off.svg',            on: 'icon:sidebar offline:medikal:On.svg'            },
  { name: 'Megaphone',         off: 'icon:sidebar offline:megaphone:Off.svg',          on: 'icon:sidebar offline:megaphone:On.svg'          },
  { name: 'Payable',           off: 'icon:sidebar offline:payable:Off.svg',            on: 'icon:sidebar offline:payable:On.svg'            },
  { name: 'Principal',         off: 'icon:sidebar offline:principal:Off.svg',          on: 'icon:sidebar offline:principal:On.svg'          },
  { name: 'Smart Forecasting', off: 'icon:sidebar offline:smart Forecasting:Off.svg',  on: 'icon:sidebar offline:smart Forecasting:On.svg'  },
];

export const ONLINE = [
  { name: 'Chat',         off: 'icon:sidebar online:chat:off.svg',         on: 'icon:sidebar online:chat:on.svg'         },
  { name: 'Dashboard',    off: 'icon:sidebar online:dashboard:off.svg',    on: 'icon:sidebar online:dashboard:on.svg'    },
  { name: 'Dekorasi',     off: 'icon:sidebar online:dekorasi:off.svg',     on: 'icon:sidebar online:dekorasi:on.svg'     },
  { name: 'Help',         off: 'icon:sidebar online:help:off.svg',         on: 'icon:sidebar online:help:on.svg'         },
  { name: 'Laporan',      off: 'icon:sidebar online:laporan:off.svg',      on: 'icon:sidebar online:laporan:on.svg'      },
  { name: 'Notification', off: 'icon:sidebar online:notification:off.svg', on: 'icon:sidebar online:notification:on.svg' },
  { name: 'Pesanan',      off: 'icon:sidebar online:pesanan:off.svg',      on: 'icon:sidebar online:pesanan:on.svg'      },
  { name: 'Produk',       off: 'icon:sidebar online:produk:off.svg',       on: 'icon:sidebar online:produk:on.svg'       },
  { name: 'Promo',        off: 'icon:sidebar online:promo:off.svg',        on: 'icon:sidebar online:promo:on.svg'        },
  { name: 'Resep',        off: 'icon:sidebar online:resep:off.svg',        on: 'icon:sidebar online:resep:on.svg'        },
  { name: 'User',         off: 'icon:sidebar online:user:off.svg',         on: 'icon:sidebar online:user:on.svg'         },
];

export const sizes = [
  { token: 'small',  px: '16px', tw: 'w-4 h-4',   cssVar: '--icon-size-small',  ctx: 'Badge, chip, inline icon'        },
  { token: 'medium', px: '24px', tw: 'w-6 h-6',   cssVar: '--icon-size-medium', ctx: 'Button, input, nav item'         },
  { token: 'large',  px: '32px', tw: 'w-8 h-8',   cssVar: '--icon-size-large',  ctx: 'Card header, empty state'        },
  { token: 'xlarge', px: '48px', tw: 'w-12 h-12', cssVar: '--icon-size-xlarge', ctx: 'Hero, error page, onboarding'    },
];
